/* colorizer.c generated by valac 0.10.0, the Vala compiler
 * generated from colorizer.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <Scintilla.h>
#include <SciLexer.h>
#include <ScintillaWidget.h>
#include <gdk/gdk.h>


#define GEANY_TYPE_FACELIFT_UI (geany_facelift_ui_get_type ())
#define GEANY_FACELIFT_UI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_TYPE_FACELIFT_UI, GeanyFaceliftUI))
#define GEANY_FACELIFT_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_TYPE_FACELIFT_UI, GeanyFaceliftUIClass))
#define GEANY_IS_FACELIFT_UI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_TYPE_FACELIFT_UI))
#define GEANY_IS_FACELIFT_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_TYPE_FACELIFT_UI))
#define GEANY_FACELIFT_UI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_TYPE_FACELIFT_UI, GeanyFaceliftUIClass))

typedef struct _GeanyFaceliftUI GeanyFaceliftUI;
typedef struct _GeanyFaceliftUIClass GeanyFaceliftUIClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))


extern GeanyPlugin* geany_plugin;
GeanyPlugin* geany_plugin = NULL;
extern GeanyData* geany_data;
GeanyData* geany_data = NULL;
extern GeanyFunctions* geany_functions;
GeanyFunctions* geany_functions = NULL;
extern ScintillaObject* sci;
ScintillaObject* sci = NULL;
extern GeanyFaceliftUI* ui;
GeanyFaceliftUI* ui = NULL;
extern gint foreground_colors[33];
gint foreground_colors[33] = {0};
extern gint background_colors[33];
gint background_colors[33] = {0};
extern gboolean fonts_bold[33];
gboolean fonts_bold[33] = {0};
extern gboolean fonts_italic[33];
gboolean fonts_italic[33] = {0};
extern gboolean fonts_underline[33];
gboolean fonts_underline[33] = {0};
extern gboolean in_message_window;
gboolean in_message_window = FALSE;
extern GtkMenuItem* sep;
GtkMenuItem* sep = NULL;
extern GtkCheckMenuItem* item;
GtkCheckMenuItem* item = NULL;
extern GtkDialog* dialog;
GtkDialog* dialog = NULL;
extern GtkScrolledWindow* swin;
GtkScrolledWindow* swin = NULL;

void plugin_set_info (PluginInfo* info);
gint plugin_version_check (gint abi_version);
GType geany_facelift_ui_get_type (void) G_GNUC_CONST;
#define FACELIFT_INDIC (INDIC_MAX - 1)
void on_current_document_changed (GObject* ignored, struct GeanyDocument* doc);
void on_editor_notif (gint param, struct SCNotification* notif);
static void _on_editor_notif_scintilla_object_sci_notify (ScintillaObject* _sender, gint param, struct SCNotification* notif, gpointer self);
void geany_facelift_ui_set_current_lexer (GeanyFaceliftUI* self, gint value);
void geany_facelift_ui_set_current_style (GeanyFaceliftUI* self, gint value);
gboolean colorize_editor (void);
gint geany_facelift_ui_get_current_style (GeanyFaceliftUI* self);
void geany_facelift_ui_set_current_foreground_color (GeanyFaceliftUI* self, gint value);
void geany_facelift_ui_set_current_background_color (GeanyFaceliftUI* self, gint value);
void geany_facelift_ui_set_font_bold (GeanyFaceliftUI* self, gboolean value);
void geany_facelift_ui_set_font_italic (GeanyFaceliftUI* self, gboolean value);
void geany_facelift_ui_set_font_underline (GeanyFaceliftUI* self, gboolean value);
void on_fg_color_changed (gint new_color);
void on_bg_color_changed (gint new_color);
gboolean geany_facelift_ui_get_use_common_background (GeanyFaceliftUI* self);
void on_font_bold_toggled (gboolean font_bold);
void on_font_italic_toggled (gboolean font_italic);
void on_font_underline_toggled (gboolean font_underline);
void on_open_colorizer (void);
void on_open_toggled (void);
gboolean on_dialog_delete (void);
void on_dialog_response (gint response_id);
void plugin_init (GeanyData* data);
GeanyFaceliftUI* geany_facelift_ui_new (void);
GeanyFaceliftUI* geany_facelift_ui_construct (GType object_type);
static void _on_fg_color_changed_geany_facelift_ui_foreground_color_changed (GeanyFaceliftUI* _sender, gint color, gpointer self);
static void _on_bg_color_changed_geany_facelift_ui_background_color_changed (GeanyFaceliftUI* _sender, gint color, gpointer self);
static void _on_font_bold_toggled_geany_facelift_ui_font_bold_toggled (GeanyFaceliftUI* _sender, gboolean font_bold, gpointer self);
static void _on_font_italic_toggled_geany_facelift_ui_font_italic_toggled (GeanyFaceliftUI* _sender, gboolean font_italic, gpointer self);
static void _on_font_underline_toggled_geany_facelift_ui_font_underline_toggled (GeanyFaceliftUI* _sender, gboolean font_italic, gpointer self);
static gboolean _on_dialog_delete_gtk_widget_delete_event (GtkWidget* _sender, GdkEvent* event, gpointer self);
static void _on_dialog_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
GtkComboBox* geany_facelift_ui_get_combo_lexer (GeanyFaceliftUI* self);
GtkComboBox* geany_facelift_ui_get_combo_style (GeanyFaceliftUI* self);
static void _on_open_toggled_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender, gpointer self);
GtkWidget* plugin_configure (GtkDialog* dlg);
void plugin_cleanup (void);

const char* lexer_names[99] = {"Container", "None", "Python", "Cpp", "HTML", "XML", "Perl", "SQL", "VisualBasic", "Properties", "ErrorList", "MakeFile", "Batch", "XCode", "LaTeX", "Lua", "Diff", "Conf", "Pascal", "Avenue", "Ada", "Lisp", "Ruby", "Eiffel", "Eiffel (keywords)", "TCL", "NNCronTab", "BullAnt", "VBScript", "Baan", "MatLab", "Sol", "Asm", "Cpp (no case)", "Fortran", "F77", "CSS", "POV", "LOUT", "ESCRIPT", "PS", "NSIS", "MMIXAL", "Clarion", "Clarion (no case)", "LOT", "YAML", "TeX", "Metapost", "PowerBasic", "Forth", "Erlang", "Octave", "MSSQL", "Verilog", "Kix", "GUI4CLI", "Specman", "Au3", "APDL", "Bash", "Asn1", "VHDL", "Caml", "BlitzBasic", "PureBasic", "Haskell", "PHP Script", "TADS3", "Rebol", "Smalltalk", "FlagShip", "Csound", "FreeBasic", "Inno", "Opal", "Spice", "D", "CMAKE", "Gap", "PLM", "Progress", "ABAQUS", "Asymptote", "R", "Magik", "PowerShell", "MySQL", "Po", "Tal", "COBOL", "TACL", "SORCUS", "PowerPro", "Nimrod", "SML", "Markdown", "Txt2Tags", "A68K"};


static void __geany_vala_plugin_SET_INFO (PluginInfo *self, const char* name, const char* description, const char* version, const char* author) {
	g_return_if_fail (name != NULL);
	(*self).name = name;
	(*self).description = description;
	(*self).version = version;
	(*self).author = author;
}


void plugin_set_info (PluginInfo* info) {
	__geany_vala_plugin_SET_INFO (info, "Colorizer", "Set Scintilla appearances on-the-fly.", "0.1", "Matthew Brush <mbrush@leftclick.ca>");
}


static gint __geany_vala_plugin_VERSION_CHECK (gint abi_version, gint api_required) {
	gint result = 0;
	if (abi_version != GEANY_ABI_VERSION) {
		result = -1;
		return result;
	}
	if (GEANY_API_VERSION < api_required) {
		result = api_required;
		return result;
	}
	result = 0;
	return result;
}


gint plugin_version_check (gint abi_version) {
	gint result = 0;
	result = __geany_vala_plugin_VERSION_CHECK (abi_version, 185);
	return result;
}


static void _on_editor_notif_scintilla_object_sci_notify (ScintillaObject* _sender, gint param, struct SCNotification* notif, gpointer self) {
	on_editor_notif (param, notif);
}


void on_current_document_changed (GObject* ignored, struct GeanyDocument* doc) {
	g_return_if_fail (ignored != NULL);
	g_return_if_fail (doc != NULL);
	if (doc->editor->sci != NULL) {
		glong len;
		sci = (ScintillaObject*) doc->editor->sci;
		len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
		if (len > 0) {
			glong pos;
			if (sci != NULL) {
				g_signal_connect (sci, "sci-notify", (GCallback) _on_editor_notif_scintilla_object_sci_notify, NULL);
			}
			geany_facelift_ui_set_current_lexer (ui, (gint) scintilla_send_message (sci, (unsigned int) SCI_GETLEXER, (uptr_t) 0, (sptr_t) 0));
			pos = scintilla_send_message (sci, (unsigned int) SCI_GETCURRENTPOS, (uptr_t) 0, (sptr_t) 0);
			geany_facelift_ui_set_current_style (ui, (gint) scintilla_send_message (sci, (unsigned int) SCI_GETSTYLEAT, (uptr_t) ((gulong) pos), (sptr_t) 0));
			scintilla_send_message (sci, (unsigned int) SCI_STYLECLEARALL, (uptr_t) 0, (sptr_t) 0);
			{
				gint i;
				i = 0;
				{
					gboolean _tmp0_;
					_tmp0_ = TRUE;
					while (TRUE) {
						if (!_tmp0_) {
							i++;
						}
						_tmp0_ = FALSE;
						if (!(i < 33)) {
							break;
						}
						foreground_colors[i] = 0x000000;
						background_colors[i] = 0xffffff;
						fonts_bold[i] = FALSE;
						fonts_italic[i] = FALSE;
						fonts_underline[i] = FALSE;
					}
				}
			}
			scintilla_send_message (sci, (unsigned int) SCI_INDICSETSTYLE, (uptr_t) ((gulong) FACELIFT_INDIC), (sptr_t) ((glong) INDIC_SQUIGGLE));
			scintilla_send_message (sci, (unsigned int) SCI_INDICSETFORE, (uptr_t) ((gulong) FACELIFT_INDIC), (sptr_t) ((glong) 0xBFBFBF));
		}
	}
}


gboolean colorize_editor (void) {
	gboolean result = FALSE;
	if (sci != NULL) {
		glong len;
		len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
		if (len > 0) {
			glong pos;
			glong num_chars;
			geany_facelift_ui_set_current_lexer (ui, (gint) scintilla_send_message (sci, (unsigned int) SCI_GETLEXER, (uptr_t) 0, (sptr_t) 0));
			pos = scintilla_send_message (sci, (unsigned int) SCI_GETCURRENTPOS, (uptr_t) 0, (sptr_t) 0);
			geany_facelift_ui_set_current_style (ui, (gint) scintilla_send_message (sci, (unsigned int) SCI_GETSTYLEAT, (uptr_t) ((gulong) pos), (sptr_t) 0));
			{
				gint i;
				i = 0;
				{
					gboolean _tmp0_;
					_tmp0_ = TRUE;
					while (TRUE) {
						if (!_tmp0_) {
							i++;
						}
						_tmp0_ = FALSE;
						if (!(i <= STYLE_DEFAULT)) {
							break;
						}
						scintilla_send_message (sci, (unsigned int) SCI_STYLESETFORE, (uptr_t) ((gulong) i), (sptr_t) ((glong) foreground_colors[i]));
						scintilla_send_message (sci, (unsigned int) SCI_STYLESETBACK, (uptr_t) ((gulong) i), (sptr_t) ((glong) background_colors[i]));
						scintilla_send_message (sci, (unsigned int) SCI_STYLESETBOLD, (uptr_t) ((gulong) i), (sptr_t) ((glong) fonts_bold[i]));
						scintilla_send_message (sci, (unsigned int) SCI_STYLESETITALIC, (uptr_t) ((gulong) i), (sptr_t) ((glong) fonts_italic[i]));
						scintilla_send_message (sci, (unsigned int) SCI_STYLESETUNDERLINE, (uptr_t) ((gulong) i), (sptr_t) ((glong) fonts_underline[i]));
					}
				}
			}
			num_chars = scintilla_send_message (sci, (unsigned int) SCI_GETTEXTLENGTH, (uptr_t) 0, (sptr_t) 0);
			scintilla_send_message (sci, (unsigned int) SCI_SETINDICATORCURRENT, (uptr_t) ((gulong) FACELIFT_INDIC), (sptr_t) 0);
			scintilla_send_message (sci, (unsigned int) SCI_INDICATORCLEARRANGE, (uptr_t) ((gulong) 0), (sptr_t) num_chars);
			scintilla_send_message (sci, (unsigned int) SCI_SETCARETLINEVISIBLE, (uptr_t) ((gulong) 0), (sptr_t) 0);
			geany_facelift_ui_set_current_foreground_color (ui, foreground_colors[geany_facelift_ui_get_current_style (ui)]);
			geany_facelift_ui_set_current_background_color (ui, background_colors[geany_facelift_ui_get_current_style (ui)]);
			geany_facelift_ui_set_font_bold (ui, fonts_bold[geany_facelift_ui_get_current_style (ui)]);
			geany_facelift_ui_set_font_italic (ui, fonts_italic[geany_facelift_ui_get_current_style (ui)]);
			geany_facelift_ui_set_font_underline (ui, fonts_underline[geany_facelift_ui_get_current_style (ui)]);
		}
	}
	result = TRUE;
	return result;
}


void on_editor_notif (gint param, struct SCNotification* notif) {
	if ((*notif).nmhdr.code == SCN_UPDATEUI) {
		colorize_editor ();
	}
}


void on_fg_color_changed (gint new_color) {
	glong len;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
	if (len > 0) {
		_tmp1_ = geany_facelift_ui_get_current_style (ui) >= 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = geany_facelift_ui_get_current_style (ui) <= 32;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		foreground_colors[geany_facelift_ui_get_current_style (ui)] = new_color;
		scintilla_send_message (sci, (unsigned int) SCI_STYLESETFORE, (uptr_t) ((gulong) geany_facelift_ui_get_current_style (ui)), (sptr_t) ((glong) new_color));
	}
}


void on_bg_color_changed (gint new_color) {
	glong len;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
	if (len > 0) {
		_tmp1_ = geany_facelift_ui_get_current_style (ui) >= 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = geany_facelift_ui_get_current_style (ui) <= 32;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		if (geany_facelift_ui_get_use_common_background (ui)) {
			{
				gint i;
				i = 0;
				{
					gboolean _tmp2_;
					_tmp2_ = TRUE;
					while (TRUE) {
						if (!_tmp2_) {
							i++;
						}
						_tmp2_ = FALSE;
						if (!(i <= STYLE_DEFAULT)) {
							break;
						}
						background_colors[i] = new_color;
						scintilla_send_message (sci, (unsigned int) SCI_STYLESETBACK, (uptr_t) ((gulong) i), (sptr_t) ((glong) new_color));
					}
				}
			}
		} else {
			background_colors[geany_facelift_ui_get_current_style (ui)] = new_color;
			scintilla_send_message (sci, (unsigned int) SCI_STYLESETBACK, (uptr_t) ((gulong) geany_facelift_ui_get_current_style (ui)), (sptr_t) ((glong) new_color));
		}
	}
}


void on_font_bold_toggled (gboolean font_bold) {
	glong len;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
	if (len > 0) {
		_tmp1_ = geany_facelift_ui_get_current_style (ui) >= 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = geany_facelift_ui_get_current_style (ui) <= 32;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		fonts_bold[geany_facelift_ui_get_current_style (ui)] = font_bold;
		scintilla_send_message (sci, (unsigned int) SCI_STYLESETBOLD, (uptr_t) ((gulong) geany_facelift_ui_get_current_style (ui)), (sptr_t) ((glong) font_bold));
	}
}


void on_font_italic_toggled (gboolean font_italic) {
	glong len;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
	if (len > 0) {
		_tmp1_ = geany_facelift_ui_get_current_style (ui) >= 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = geany_facelift_ui_get_current_style (ui) <= 32;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		fonts_italic[geany_facelift_ui_get_current_style (ui)] = font_italic;
		scintilla_send_message (sci, (unsigned int) SCI_STYLESETITALIC, (uptr_t) ((gulong) geany_facelift_ui_get_current_style (ui)), (sptr_t) ((glong) font_italic));
	}
}


void on_font_underline_toggled (gboolean font_underline) {
	glong len;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	len = scintilla_send_message (sci, (unsigned int) SCI_GETLENGTH, (uptr_t) 0, (sptr_t) 0);
	if (len > 0) {
		_tmp1_ = geany_facelift_ui_get_current_style (ui) >= 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = geany_facelift_ui_get_current_style (ui) <= 32;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		fonts_underline[geany_facelift_ui_get_current_style (ui)] = font_underline;
		scintilla_send_message (sci, (unsigned int) SCI_STYLESETUNDERLINE, (uptr_t) ((gulong) geany_facelift_ui_get_current_style (ui)), (sptr_t) ((glong) font_underline));
	}
}


void on_open_colorizer (void) {
	glong pos;
	if (sci == NULL) {
		return;
	}
	geany_facelift_ui_set_current_lexer (ui, (gint) scintilla_send_message (sci, (unsigned int) SCI_GETLEXER, (uptr_t) 0, (sptr_t) 0));
	pos = scintilla_send_message (sci, (unsigned int) SCI_GETCURRENTPOS, (uptr_t) 0, (sptr_t) 0);
	geany_facelift_ui_set_current_style (ui, (gint) scintilla_send_message (sci, (unsigned int) SCI_GETSTYLEAT, (uptr_t) ((gulong) pos), (sptr_t) 0));
}


void on_open_toggled (void) {
	gboolean state;
	if (sci == NULL) {
		return;
	}
	state = gtk_check_menu_item_get_active (item);
	if (state) {
		if (in_message_window) {
			gtk_widget_show_all ((GtkWidget*) swin);
		} else {
			gtk_widget_show ((GtkWidget*) dialog);
		}
	} else {
		if (in_message_window) {
			gtk_widget_hide ((GtkWidget*) swin);
		} else {
			gtk_widget_hide ((GtkWidget*) dialog);
		}
	}
}


gboolean on_dialog_delete (void) {
	gboolean result = FALSE;
	if (!in_message_window) {
		gtk_widget_hide ((GtkWidget*) dialog);
		gtk_check_menu_item_set_active (item, FALSE);
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


void on_dialog_response (gint response_id) {
	if (!in_message_window) {
		gtk_widget_hide ((GtkWidget*) dialog);
		gtk_check_menu_item_set_active (item, FALSE);
	}
}


static void _on_fg_color_changed_geany_facelift_ui_foreground_color_changed (GeanyFaceliftUI* _sender, gint color, gpointer self) {
	on_fg_color_changed (color);
}


static void _on_bg_color_changed_geany_facelift_ui_background_color_changed (GeanyFaceliftUI* _sender, gint color, gpointer self) {
	on_bg_color_changed (color);
}


static void _on_font_bold_toggled_geany_facelift_ui_font_bold_toggled (GeanyFaceliftUI* _sender, gboolean font_bold, gpointer self) {
	on_font_bold_toggled (font_bold);
}


static void _on_font_italic_toggled_geany_facelift_ui_font_italic_toggled (GeanyFaceliftUI* _sender, gboolean font_italic, gpointer self) {
	on_font_italic_toggled (font_italic);
}


static void _on_font_underline_toggled_geany_facelift_ui_font_underline_toggled (GeanyFaceliftUI* _sender, gboolean font_italic, gpointer self) {
	on_font_underline_toggled (font_italic);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _on_dialog_delete_gtk_widget_delete_event (GtkWidget* _sender, GdkEvent* event, gpointer self) {
	gboolean result;
	result = on_dialog_delete ();
	return result;
}


static void _on_dialog_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	on_dialog_response (response_id);
}


static void _on_open_toggled_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender, gpointer self) {
	on_open_toggled ();
}


void plugin_init (GeanyData* data) {
	struct GeanyDocument* doc;
	GeanyFaceliftUI* _tmp0_;
	GtkComboBox* cb;
	GtkComboBox* _tmp6_;
	GtkMenuShell* menu;
	GtkMenuItem* _tmp9_;
	GtkCheckMenuItem* _tmp10_;
	g_return_if_fail (data != NULL);
	doc = document_get_current ();
	if (doc != NULL) {
		sci = (ScintillaObject*) doc->editor->sci;
	}
	plugin_signal_connect (geany_plugin, NULL, "document-activate", TRUE, (GCallback) on_current_document_changed, NULL);
	plugin_signal_connect (geany_plugin, NULL, "document-open", TRUE, (GCallback) on_current_document_changed, NULL);
	plugin_signal_connect (geany_plugin, NULL, "document-new", TRUE, (GCallback) on_current_document_changed, NULL);
	ui = (_tmp0_ = g_object_ref_sink (geany_facelift_ui_new ()), _g_object_unref0 (ui), _tmp0_);
	g_signal_connect (ui, "foreground-color-changed", (GCallback) _on_fg_color_changed_geany_facelift_ui_foreground_color_changed, NULL);
	g_signal_connect (ui, "background-color-changed", (GCallback) _on_bg_color_changed_geany_facelift_ui_background_color_changed, NULL);
	g_signal_connect (ui, "font-bold-toggled", (GCallback) _on_font_bold_toggled_geany_facelift_ui_font_bold_toggled, NULL);
	g_signal_connect (ui, "font-italic-toggled", (GCallback) _on_font_italic_toggled_geany_facelift_ui_font_italic_toggled, NULL);
	g_signal_connect (ui, "font-underline-toggled", (GCallback) _on_font_underline_toggled_geany_facelift_ui_font_underline_toggled, NULL);
	if (in_message_window) {
		GtkScrolledWindow* _tmp1_;
		GtkNotebook* _tmp2_;
		GtkNotebook* nb;
		swin = (_tmp1_ = g_object_ref_sink ((GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL)), _g_object_unref0 (swin), _tmp1_);
		gtk_scrolled_window_set_policy (swin, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
		gtk_scrolled_window_add_with_viewport (swin, (GtkWidget*) ui);
		nb = _g_object_ref0 ((_tmp2_ = data->main_widgets->message_window_notebook, GTK_IS_NOTEBOOK (_tmp2_) ? ((GtkNotebook*) _tmp2_) : NULL));
		if (nb != NULL) {
			GtkLabel* _tmp3_;
			gtk_notebook_append_page (nb, (GtkWidget*) swin, (GtkWidget*) (_tmp3_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("Colorizer"))));
			_g_object_unref0 (_tmp3_);
			gtk_widget_hide ((GtkWidget*) swin);
		}
		_g_object_unref0 (nb);
	} else {
		GtkDialog* _tmp4_;
		GtkBox* box;
		dialog = (_tmp4_ = g_object_ref_sink ((GtkDialog*) gtk_dialog_new_with_buttons ("Colorizer", GTK_WINDOW (geany_data->main_widgets->window), GTK_DIALOG_DESTROY_WITH_PARENT, GTK_STOCK_CLOSE, GTK_RESPONSE_ACCEPT, NULL)), _g_object_unref0 (dialog), _tmp4_);
		g_signal_connect ((GtkWidget*) dialog, "delete-event", (GCallback) _on_dialog_delete_gtk_widget_delete_event, NULL);
		g_signal_connect (dialog, "response", (GCallback) _on_dialog_response_gtk_dialog_response, NULL);
		box = _g_object_ref0 (GTK_BOX (gtk_dialog_get_content_area (dialog)));
		gtk_box_pack_start (box, (GtkWidget*) ui, TRUE, TRUE, (guint) 0);
		_g_object_unref0 (box);
	}
	cb = _g_object_ref0 (geany_facelift_ui_get_combo_lexer (ui));
	{
		gint i;
		i = 0;
		{
			gboolean _tmp5_;
			_tmp5_ = TRUE;
			while (TRUE) {
				if (!_tmp5_) {
					i++;
				}
				_tmp5_ = FALSE;
				if (!(i < G_N_ELEMENTS (lexer_names))) {
					break;
				}
				gtk_combo_box_append_text (cb, lexer_names[i]);
			}
		}
	}
	cb = (_tmp6_ = _g_object_ref0 (geany_facelift_ui_get_combo_style (ui)), _g_object_unref0 (cb), _tmp6_);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp7_;
			_tmp7_ = TRUE;
			while (TRUE) {
				char* _tmp8_;
				if (!_tmp7_) {
					i++;
				}
				_tmp7_ = FALSE;
				if (!(i <= STYLE_DEFAULT)) {
					break;
				}
				gtk_combo_box_append_text (cb, _tmp8_ = g_strdup_printf ("Style #%d", i));
				_g_free0 (_tmp8_);
			}
		}
	}
	menu = GTK_MENU_SHELL (geany_data->main_widgets->tools_menu);
	sep = (_tmp9_ = (GtkMenuItem*) g_object_ref_sink ((GtkSeparatorMenuItem*) gtk_separator_menu_item_new ()), _g_object_unref0 (sep), _tmp9_);
	gtk_menu_shell_append (menu, (GtkWidget*) sep);
	item = (_tmp10_ = g_object_ref_sink ((GtkCheckMenuItem*) gtk_check_menu_item_new_with_label ("Colorizer")), _g_object_unref0 (item), _tmp10_);
	g_signal_connect (item, "toggled", (GCallback) _on_open_toggled_gtk_check_menu_item_toggled, NULL);
	gtk_menu_shell_append (menu, (GtkWidget*) ((GtkMenuItem*) item));
	gtk_widget_show ((GtkWidget*) item);
	plugin_module_make_resident (geany_plugin);
	_g_object_unref0 (cb);
}


GtkWidget* plugin_configure (GtkDialog* dlg) {
	GtkWidget* result = NULL;
	GtkVBox* vb;
	GtkCheckButton* cb;
	g_return_val_if_fail (dlg != NULL, NULL);
	vb = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 0));
	cb = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label ("Show in separate dialog instead of message window."));
	gtk_box_pack_start ((GtkBox*) vb, (GtkWidget*) cb, FALSE, TRUE, 0);
	result = (GtkWidget*) vb;
	_g_object_unref0 (cb);
	return result;
}


void plugin_cleanup (void) {
	gtk_object_destroy ((GtkObject*) sep);
	gtk_object_destroy ((GtkObject*) item);
	if (dialog != NULL) {
		gtk_object_destroy ((GtkObject*) dialog);
	}
	if (swin != NULL) {
		gtk_object_destroy ((GtkObject*) swin);
	}
}




