/* colorizerui.c generated by valac 0.10.0, the Vala compiler
 * generated from colorizerui.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <string.h>


#define GEANY_TYPE_COLORIZER_UI (geany_colorizer_ui_get_type ())
#define GEANY_COLORIZER_UI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_TYPE_COLORIZER_UI, GeanyColorizerUI))
#define GEANY_COLORIZER_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_TYPE_COLORIZER_UI, GeanyColorizerUIClass))
#define GEANY_IS_COLORIZER_UI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_TYPE_COLORIZER_UI))
#define GEANY_IS_COLORIZER_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_TYPE_COLORIZER_UI))
#define GEANY_COLORIZER_UI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_TYPE_COLORIZER_UI, GeanyColorizerUIClass))

typedef struct _GeanyColorizerUI GeanyColorizerUI;
typedef struct _GeanyColorizerUIClass GeanyColorizerUIClass;
typedef struct _GeanyColorizerUIPrivate GeanyColorizerUIPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GeanyColorizerUI {
	GtkVBox parent_instance;
	GeanyColorizerUIPrivate * priv;
};

struct _GeanyColorizerUIClass {
	GtkVBoxClass parent_class;
};

struct _GeanyColorizerUIPrivate {
	GtkComboBox* comboLexer;
	GtkComboBox* comboStyle;
	GtkNotebook* notebookMain;
	GtkColorSelection* colorselForeground;
	GtkColorSelection* colorselBackground;
	GtkCheckButton* checkUseCommonBackground;
	GtkCheckButton* checkFontBold;
	GtkCheckButton* checkFontItalic;
	GtkCheckButton* checkFontUnderline;
};


static gpointer geany_colorizer_ui_parent_class = NULL;

GType geany_colorizer_ui_get_type (void) G_GNUC_CONST;
#define GEANY_COLORIZER_UI_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_TYPE_COLORIZER_UI, GeanyColorizerUIPrivate))
enum  {
	GEANY_COLORIZER_UI_DUMMY_PROPERTY,
	GEANY_COLORIZER_UI_COMBO_LEXER,
	GEANY_COLORIZER_UI_COMBO_STYLE,
	GEANY_COLORIZER_UI_CURRENT_LEXER,
	GEANY_COLORIZER_UI_CURRENT_STYLE,
	GEANY_COLORIZER_UI_CURRENT_FOREGROUND_COLOR,
	GEANY_COLORIZER_UI_CURRENT_BACKGROUND_COLOR,
	GEANY_COLORIZER_UI_FONT_BOLD,
	GEANY_COLORIZER_UI_FONT_ITALIC,
	GEANY_COLORIZER_UI_FONT_UNDERLINE,
	GEANY_COLORIZER_UI_USE_COMMON_BACKGROUND
};
GeanyColorizerUI* geany_colorizer_ui_new (void);
GeanyColorizerUI* geany_colorizer_ui_construct (GType object_type);
void geany_colorizer_ui_init_ui (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_combo_lexer_changed (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_combo_style_changed (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_notebook_page_switched (GeanyColorizerUI* self, GtkNotebookPage* page, guint page_num);
static void geany_colorizer_ui_on_fg_color_changed (GeanyColorizerUI* self);
gint geany_colorizer_ui_int_from_color (GdkColor* c);
static void geany_colorizer_ui_on_bg_color_changed (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_use_common_bg_color_toggled (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_font_bold_toggled (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_font_italic_toggled (GeanyColorizerUI* self);
static void geany_colorizer_ui_on_font_underline_toggled (GeanyColorizerUI* self);
void geany_colorizer_ui_connect_signals (GeanyColorizerUI* self);
static void _geany_colorizer_ui_on_combo_lexer_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
static void _geany_colorizer_ui_on_combo_style_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
static void _geany_colorizer_ui_on_notebook_page_switched_gtk_notebook_switch_page (GtkNotebook* _sender, GtkNotebookPage* page, guint page_num, gpointer self);
static void _geany_colorizer_ui_on_fg_color_changed_gtk_color_selection_color_changed (GtkColorSelection* _sender, gpointer self);
static void _geany_colorizer_ui_on_bg_color_changed_gtk_color_selection_color_changed (GtkColorSelection* _sender, gpointer self);
static void _geany_colorizer_ui_on_use_common_bg_color_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _geany_colorizer_ui_on_font_bold_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _geany_colorizer_ui_on_font_italic_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _geany_colorizer_ui_on_font_underline_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static double geany_colorizer_ui_scale_round (double val, double factor);
void geany_colorizer_ui_color_from_int (gint color, GdkColor* result);
GtkComboBox* geany_colorizer_ui_get_combo_lexer (GeanyColorizerUI* self);
GtkComboBox* geany_colorizer_ui_get_combo_style (GeanyColorizerUI* self);
gint geany_colorizer_ui_get_current_lexer (GeanyColorizerUI* self);
void geany_colorizer_ui_set_current_lexer (GeanyColorizerUI* self, gint value);
gint geany_colorizer_ui_get_current_style (GeanyColorizerUI* self);
void geany_colorizer_ui_set_current_style (GeanyColorizerUI* self, gint value);
gint geany_colorizer_ui_get_current_foreground_color (GeanyColorizerUI* self);
void geany_colorizer_ui_set_current_foreground_color (GeanyColorizerUI* self, gint value);
gint geany_colorizer_ui_get_current_background_color (GeanyColorizerUI* self);
void geany_colorizer_ui_set_current_background_color (GeanyColorizerUI* self, gint value);
gboolean geany_colorizer_ui_get_font_bold (GeanyColorizerUI* self);
void geany_colorizer_ui_set_font_bold (GeanyColorizerUI* self, gboolean value);
gboolean geany_colorizer_ui_get_font_italic (GeanyColorizerUI* self);
void geany_colorizer_ui_set_font_italic (GeanyColorizerUI* self, gboolean value);
gboolean geany_colorizer_ui_get_font_underline (GeanyColorizerUI* self);
void geany_colorizer_ui_set_font_underline (GeanyColorizerUI* self, gboolean value);
gboolean geany_colorizer_ui_get_use_common_background (GeanyColorizerUI* self);
void geany_colorizer_ui_set_use_common_background (GeanyColorizerUI* self, gboolean value);
static void geany_colorizer_ui_finalize (GObject* obj);
static void geany_colorizer_ui_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void geany_colorizer_ui_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



GeanyColorizerUI* geany_colorizer_ui_construct (GType object_type) {
	GeanyColorizerUI * self;
	self = g_object_newv (object_type, 0, NULL);
	geany_colorizer_ui_init_ui (self);
	return self;
}


GeanyColorizerUI* geany_colorizer_ui_new (void) {
	return geany_colorizer_ui_construct (GEANY_TYPE_COLORIZER_UI);
}


static void geany_colorizer_ui_on_combo_lexer_changed (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "lexer-changed", gtk_combo_box_get_active (self->priv->comboLexer));
}


static void geany_colorizer_ui_on_combo_style_changed (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "style-changed", gtk_combo_box_get_active (self->priv->comboStyle));
}


static void geany_colorizer_ui_on_notebook_page_switched (GeanyColorizerUI* self, GtkNotebookPage* page, guint page_num) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (page != NULL);
	g_signal_emit_by_name (self, "notebook-page-switched", (gint) page_num);
}


static void geany_colorizer_ui_on_fg_color_changed (GeanyColorizerUI* self) {
	GdkColor _tmp0_ = {0};
	GdkColor _tmp1_;
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "foreground-color-changed", geany_colorizer_ui_int_from_color ((_tmp1_ = (gtk_color_selection_get_current_color (self->priv->colorselForeground, &_tmp0_), _tmp0_), &_tmp1_)));
}


static void geany_colorizer_ui_on_bg_color_changed (GeanyColorizerUI* self) {
	GdkColor _tmp0_ = {0};
	GdkColor _tmp1_;
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "background-color-changed", geany_colorizer_ui_int_from_color ((_tmp1_ = (gtk_color_selection_get_current_color (self->priv->colorselBackground, &_tmp0_), _tmp0_), &_tmp1_)));
}


static void geany_colorizer_ui_on_use_common_bg_color_toggled (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "use-common-bg-color-toggled", gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkUseCommonBackground));
}


static void geany_colorizer_ui_on_font_bold_toggled (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "font-bold-toggled", gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkFontBold));
}


static void geany_colorizer_ui_on_font_italic_toggled (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "font-italic-toggled", gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkFontItalic));
}


static void geany_colorizer_ui_on_font_underline_toggled (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "font-underline-toggled", gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkFontUnderline));
}


static void _geany_colorizer_ui_on_combo_lexer_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	geany_colorizer_ui_on_combo_lexer_changed (self);
}


static void _geany_colorizer_ui_on_combo_style_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	geany_colorizer_ui_on_combo_style_changed (self);
}


static void _geany_colorizer_ui_on_notebook_page_switched_gtk_notebook_switch_page (GtkNotebook* _sender, GtkNotebookPage* page, guint page_num, gpointer self) {
	geany_colorizer_ui_on_notebook_page_switched (self, page, page_num);
}


static void _geany_colorizer_ui_on_fg_color_changed_gtk_color_selection_color_changed (GtkColorSelection* _sender, gpointer self) {
	geany_colorizer_ui_on_fg_color_changed (self);
}


static void _geany_colorizer_ui_on_bg_color_changed_gtk_color_selection_color_changed (GtkColorSelection* _sender, gpointer self) {
	geany_colorizer_ui_on_bg_color_changed (self);
}


static void _geany_colorizer_ui_on_use_common_bg_color_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	geany_colorizer_ui_on_use_common_bg_color_toggled (self);
}


static void _geany_colorizer_ui_on_font_bold_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	geany_colorizer_ui_on_font_bold_toggled (self);
}


static void _geany_colorizer_ui_on_font_italic_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	geany_colorizer_ui_on_font_italic_toggled (self);
}


static void _geany_colorizer_ui_on_font_underline_toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	geany_colorizer_ui_on_font_underline_toggled (self);
}


void geany_colorizer_ui_connect_signals (GeanyColorizerUI* self) {
	g_return_if_fail (self != NULL);
	g_signal_connect_object (self->priv->comboLexer, "changed", (GCallback) _geany_colorizer_ui_on_combo_lexer_changed_gtk_combo_box_changed, self, 0);
	g_signal_connect_object (self->priv->comboStyle, "changed", (GCallback) _geany_colorizer_ui_on_combo_style_changed_gtk_combo_box_changed, self, 0);
	g_signal_connect_object (self->priv->notebookMain, "switch-page", (GCallback) _geany_colorizer_ui_on_notebook_page_switched_gtk_notebook_switch_page, self, 0);
	g_signal_connect_object (self->priv->colorselForeground, "color-changed", (GCallback) _geany_colorizer_ui_on_fg_color_changed_gtk_color_selection_color_changed, self, 0);
	g_signal_connect_object (self->priv->colorselBackground, "color-changed", (GCallback) _geany_colorizer_ui_on_bg_color_changed_gtk_color_selection_color_changed, self, 0);
	g_signal_connect_object ((GtkToggleButton*) self->priv->checkUseCommonBackground, "toggled", (GCallback) _geany_colorizer_ui_on_use_common_bg_color_toggled_gtk_toggle_button_toggled, self, 0);
	g_signal_connect_object ((GtkToggleButton*) self->priv->checkFontBold, "toggled", (GCallback) _geany_colorizer_ui_on_font_bold_toggled_gtk_toggle_button_toggled, self, 0);
	g_signal_connect_object ((GtkToggleButton*) self->priv->checkFontItalic, "toggled", (GCallback) _geany_colorizer_ui_on_font_italic_toggled_gtk_toggle_button_toggled, self, 0);
	g_signal_connect_object ((GtkToggleButton*) self->priv->checkFontUnderline, "toggled", (GCallback) _geany_colorizer_ui_on_font_underline_toggled_gtk_toggle_button_toggled, self, 0);
}


void geany_colorizer_ui_init_ui (GeanyColorizerUI* self) {
	GtkComboBox* _tmp0_;
	GtkComboBox* _tmp1_;
	GtkNotebook* _tmp2_;
	GtkColorSelection* _tmp3_;
	GtkColorSelection* _tmp4_;
	GtkCheckButton* _tmp5_;
	GtkCheckButton* _tmp6_;
	GtkCheckButton* _tmp7_;
	GtkCheckButton* _tmp8_;
	GtkHBox* hbox;
	GtkLabel* _tmp9_;
	GtkLabel* _tmp10_;
	GtkHSeparator* _tmp11_;
	GtkVBox* vbox;
	GtkLabel* _tmp12_;
	GtkHBox* _tmp13_;
	GtkVBox* _tmp14_;
	GtkHSeparator* _tmp15_;
	GtkLabel* _tmp16_;
	GtkHBox* _tmp17_;
	GtkVBox* _tmp18_;
	GtkLabel* _tmp19_;
	g_return_if_fail (self != NULL);
	self->priv->comboLexer = (_tmp0_ = g_object_ref_sink ((GtkComboBox*) gtk_combo_box_new_text ()), _g_object_unref0 (self->priv->comboLexer), _tmp0_);
	self->priv->comboStyle = (_tmp1_ = g_object_ref_sink ((GtkComboBox*) gtk_combo_box_new_text ()), _g_object_unref0 (self->priv->comboStyle), _tmp1_);
	self->priv->notebookMain = (_tmp2_ = g_object_ref_sink ((GtkNotebook*) gtk_notebook_new ()), _g_object_unref0 (self->priv->notebookMain), _tmp2_);
	self->priv->colorselForeground = (_tmp3_ = g_object_ref_sink ((GtkColorSelection*) gtk_color_selection_new ()), _g_object_unref0 (self->priv->colorselForeground), _tmp3_);
	self->priv->colorselBackground = (_tmp4_ = g_object_ref_sink ((GtkColorSelection*) gtk_color_selection_new ()), _g_object_unref0 (self->priv->colorselBackground), _tmp4_);
	self->priv->checkUseCommonBackground = (_tmp5_ = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label ("Use common background")), _g_object_unref0 (self->priv->checkUseCommonBackground), _tmp5_);
	self->priv->checkFontBold = (_tmp6_ = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label ("Bold")), _g_object_unref0 (self->priv->checkFontBold), _tmp6_);
	self->priv->checkFontItalic = (_tmp7_ = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label ("Italic")), _g_object_unref0 (self->priv->checkFontItalic), _tmp7_);
	self->priv->checkFontUnderline = (_tmp8_ = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label ("Underline")), _g_object_unref0 (self->priv->checkFontUnderline), _tmp8_);
	gtk_color_selection_set_has_opacity_control (self->priv->colorselForeground, FALSE);
	gtk_color_selection_set_has_palette (self->priv->colorselForeground, TRUE);
	gtk_box_set_homogeneous ((GtkBox*) self->priv->colorselForeground, TRUE);
	gtk_color_selection_set_has_opacity_control (self->priv->colorselBackground, FALSE);
	gtk_color_selection_set_has_palette (self->priv->colorselBackground, TRUE);
	gtk_box_set_homogeneous ((GtkBox*) self->priv->colorselBackground, TRUE);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->checkUseCommonBackground, TRUE);
	hbox = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 6));
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) (_tmp9_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("Lexer:"))), FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp9_);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) self->priv->comboLexer, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) (_tmp10_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("Style:"))), FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp10_);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) self->priv->comboStyle, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) hbox, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) (_tmp11_ = g_object_ref_sink ((GtkHSeparator*) gtk_hseparator_new ())), FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp11_);
	vbox = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 6));
	gtk_container_set_border_width ((GtkContainer*) vbox, (guint) 6);
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) self->priv->colorselForeground, TRUE, TRUE, (guint) 0);
	gtk_notebook_append_page (self->priv->notebookMain, (GtkWidget*) vbox, (GtkWidget*) (_tmp12_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("Foreground"))));
	_g_object_unref0 (_tmp12_);
	hbox = (_tmp13_ = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 6)), _g_object_unref0 (hbox), _tmp13_);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) self->priv->checkUseCommonBackground, FALSE, TRUE, (guint) 0);
	vbox = (_tmp14_ = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 6)), _g_object_unref0 (vbox), _tmp14_);
	gtk_container_set_border_width ((GtkContainer*) vbox, (guint) 6);
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) hbox, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) (_tmp15_ = g_object_ref_sink ((GtkHSeparator*) gtk_hseparator_new ())), FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp15_);
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) self->priv->colorselBackground, TRUE, TRUE, (guint) 0);
	gtk_notebook_append_page (self->priv->notebookMain, (GtkWidget*) vbox, (GtkWidget*) (_tmp16_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("Background"))));
	_g_object_unref0 (_tmp16_);
	hbox = (_tmp17_ = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 6)), _g_object_unref0 (hbox), _tmp17_);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) self->priv->checkFontBold, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) self->priv->checkFontItalic, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) self->priv->checkFontUnderline, FALSE, TRUE, (guint) 0);
	vbox = (_tmp18_ = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 6)), _g_object_unref0 (vbox), _tmp18_);
	gtk_container_set_border_width ((GtkContainer*) vbox, (guint) 6);
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) hbox, FALSE, TRUE, (guint) 0);
	gtk_notebook_append_page (self->priv->notebookMain, (GtkWidget*) vbox, (GtkWidget*) (_tmp19_ = g_object_ref_sink ((GtkLabel*) gtk_label_new ("Font"))));
	_g_object_unref0 (_tmp19_);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->notebookMain, TRUE, TRUE, (guint) 0);
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 6);
	gtk_box_set_spacing ((GtkBox*) self, 6);
	gtk_widget_show_all ((GtkWidget*) self);
	geany_colorizer_ui_connect_signals (self);
	_g_object_unref0 (vbox);
	_g_object_unref0 (hbox);
}


gint geany_colorizer_ui_int_from_color (GdkColor* c) {
	gint result = 0;
	gint r;
	gint g;
	gint b;
	r = (gint) geany_colorizer_ui_scale_round ((double) ((*c).red / 256), (double) 255);
	g = (gint) geany_colorizer_ui_scale_round ((double) ((*c).green / 256), (double) 255);
	b = (gint) geany_colorizer_ui_scale_round ((double) ((*c).blue / 256), (double) 255);
	result = ((b * 65536) + (g * 256)) + r;
	return result;
}


static double geany_colorizer_ui_scale_round (double val, double factor) {
	double result = 0.0;
	val = floor (val);
	val = fmax (val, (double) 0);
	val = fmin (val, factor);
	result = val;
	return result;
}


void geany_colorizer_ui_color_from_int (gint color, GdkColor* result) {
	GdkColor c = {0};
	gint r;
	gint g;
	gint b;
	memset (&c, 0, sizeof (GdkColor));
	r = color & 255;
	g = (color >> 16) & 255;
	b = (color >> 16) & 255;
	c.red = (guint16) (r * 256);
	c.green = (guint16) (g * 256);
	c.blue = (guint16) (b * 256);
	*result = c;
	return;
}


GtkComboBox* geany_colorizer_ui_get_combo_lexer (GeanyColorizerUI* self) {
	GtkComboBox* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->comboLexer;
	return result;
}


GtkComboBox* geany_colorizer_ui_get_combo_style (GeanyColorizerUI* self) {
	GtkComboBox* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->comboStyle;
	return result;
}


gint geany_colorizer_ui_get_current_lexer (GeanyColorizerUI* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = gtk_combo_box_get_active (self->priv->comboLexer);
	return result;
}


void geany_colorizer_ui_set_current_lexer (GeanyColorizerUI* self, gint value) {
	g_return_if_fail (self != NULL);
	gtk_combo_box_set_active (self->priv->comboLexer, value);
	g_object_notify ((GObject *) self, "current-lexer");
}


gint geany_colorizer_ui_get_current_style (GeanyColorizerUI* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = gtk_combo_box_get_active (self->priv->comboStyle);
	return result;
}


void geany_colorizer_ui_set_current_style (GeanyColorizerUI* self, gint value) {
	g_return_if_fail (self != NULL);
	gtk_combo_box_set_active (self->priv->comboStyle, value);
	g_object_notify ((GObject *) self, "current-style");
}


gint geany_colorizer_ui_get_current_foreground_color (GeanyColorizerUI* self) {
	gint result;
	GdkColor _tmp0_ = {0};
	GdkColor _tmp1_;
	g_return_val_if_fail (self != NULL, 0);
	result = geany_colorizer_ui_int_from_color ((_tmp1_ = (gtk_color_selection_get_current_color (self->priv->colorselForeground, &_tmp0_), _tmp0_), &_tmp1_));
	return result;
}


void geany_colorizer_ui_set_current_foreground_color (GeanyColorizerUI* self, gint value) {
	gint int_color;
	GdkColor _tmp0_ = {0};
	GdkColor clr;
	g_return_if_fail (self != NULL);
	int_color = value;
	clr = (geany_colorizer_ui_color_from_int (int_color, &_tmp0_), _tmp0_);
	gtk_color_selection_set_current_color (self->priv->colorselForeground, &clr);
	g_object_notify ((GObject *) self, "current-foreground-color");
}


gint geany_colorizer_ui_get_current_background_color (GeanyColorizerUI* self) {
	gint result;
	GdkColor _tmp0_ = {0};
	GdkColor _tmp1_;
	g_return_val_if_fail (self != NULL, 0);
	result = geany_colorizer_ui_int_from_color ((_tmp1_ = (gtk_color_selection_get_current_color (self->priv->colorselBackground, &_tmp0_), _tmp0_), &_tmp1_));
	return result;
}


void geany_colorizer_ui_set_current_background_color (GeanyColorizerUI* self, gint value) {
	gint int_color;
	GdkColor _tmp0_ = {0};
	GdkColor clr;
	g_return_if_fail (self != NULL);
	int_color = value;
	clr = (geany_colorizer_ui_color_from_int (int_color, &_tmp0_), _tmp0_);
	gtk_color_selection_set_current_color (self->priv->colorselBackground, &clr);
	g_object_notify ((GObject *) self, "current-background-color");
}


gboolean geany_colorizer_ui_get_font_bold (GeanyColorizerUI* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkFontBold);
	return result;
}


void geany_colorizer_ui_set_font_bold (GeanyColorizerUI* self, gboolean value) {
	g_return_if_fail (self != NULL);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->checkFontBold, value);
	g_object_notify ((GObject *) self, "font-bold");
}


gboolean geany_colorizer_ui_get_font_italic (GeanyColorizerUI* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkFontItalic);
	return result;
}


void geany_colorizer_ui_set_font_italic (GeanyColorizerUI* self, gboolean value) {
	g_return_if_fail (self != NULL);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->checkFontItalic, value);
	g_object_notify ((GObject *) self, "font-italic");
}


gboolean geany_colorizer_ui_get_font_underline (GeanyColorizerUI* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkFontUnderline);
	return result;
}


void geany_colorizer_ui_set_font_underline (GeanyColorizerUI* self, gboolean value) {
	g_return_if_fail (self != NULL);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->checkFontUnderline, value);
	g_object_notify ((GObject *) self, "font-underline");
}


gboolean geany_colorizer_ui_get_use_common_background (GeanyColorizerUI* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->checkUseCommonBackground);
	return result;
}


void geany_colorizer_ui_set_use_common_background (GeanyColorizerUI* self, gboolean value) {
	g_return_if_fail (self != NULL);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->checkUseCommonBackground, value);
	g_object_notify ((GObject *) self, "use-common-background");
}


static void geany_colorizer_ui_class_init (GeanyColorizerUIClass * klass) {
	geany_colorizer_ui_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyColorizerUIPrivate));
	G_OBJECT_CLASS (klass)->get_property = geany_colorizer_ui_get_property;
	G_OBJECT_CLASS (klass)->set_property = geany_colorizer_ui_set_property;
	G_OBJECT_CLASS (klass)->finalize = geany_colorizer_ui_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_COMBO_LEXER, g_param_spec_object ("combo-lexer", "combo-lexer", "combo-lexer", GTK_TYPE_COMBO_BOX, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_COMBO_STYLE, g_param_spec_object ("combo-style", "combo-style", "combo-style", GTK_TYPE_COMBO_BOX, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_CURRENT_LEXER, g_param_spec_int ("current-lexer", "current-lexer", "current-lexer", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_CURRENT_STYLE, g_param_spec_int ("current-style", "current-style", "current-style", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_CURRENT_FOREGROUND_COLOR, g_param_spec_int ("current-foreground-color", "current-foreground-color", "current-foreground-color", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_CURRENT_BACKGROUND_COLOR, g_param_spec_int ("current-background-color", "current-background-color", "current-background-color", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_FONT_BOLD, g_param_spec_boolean ("font-bold", "font-bold", "font-bold", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_FONT_ITALIC, g_param_spec_boolean ("font-italic", "font-italic", "font-italic", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_FONT_UNDERLINE, g_param_spec_boolean ("font-underline", "font-underline", "font-underline", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_COLORIZER_UI_USE_COMMON_BACKGROUND, g_param_spec_boolean ("use-common-background", "use-common-background", "use-common-background", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("foreground_color_changed", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
	g_signal_new ("background_color_changed", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
	g_signal_new ("lexer_changed", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
	g_signal_new ("style_changed", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
	g_signal_new ("use_common_bg_color_toggled", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
	g_signal_new ("close_button_clicked", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("notebook_page_switched", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
	g_signal_new ("font_bold_toggled", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
	g_signal_new ("font_italic_toggled", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
	g_signal_new ("font_underline_toggled", GEANY_TYPE_COLORIZER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
}


static void geany_colorizer_ui_instance_init (GeanyColorizerUI * self) {
	self->priv = GEANY_COLORIZER_UI_GET_PRIVATE (self);
}


static void geany_colorizer_ui_finalize (GObject* obj) {
	GeanyColorizerUI * self;
	self = GEANY_COLORIZER_UI (obj);
	_g_object_unref0 (self->priv->comboLexer);
	_g_object_unref0 (self->priv->comboStyle);
	_g_object_unref0 (self->priv->notebookMain);
	_g_object_unref0 (self->priv->colorselForeground);
	_g_object_unref0 (self->priv->colorselBackground);
	_g_object_unref0 (self->priv->checkUseCommonBackground);
	_g_object_unref0 (self->priv->checkFontBold);
	_g_object_unref0 (self->priv->checkFontItalic);
	_g_object_unref0 (self->priv->checkFontUnderline);
	G_OBJECT_CLASS (geany_colorizer_ui_parent_class)->finalize (obj);
}


GType geany_colorizer_ui_get_type (void) {
	static volatile gsize geany_colorizer_ui_type_id__volatile = 0;
	if (g_once_init_enter (&geany_colorizer_ui_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyColorizerUIClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_colorizer_ui_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyColorizerUI), 0, (GInstanceInitFunc) geany_colorizer_ui_instance_init, NULL };
		GType geany_colorizer_ui_type_id;
		geany_colorizer_ui_type_id = g_type_register_static (GTK_TYPE_VBOX, "GeanyColorizerUI", &g_define_type_info, 0);
		g_once_init_leave (&geany_colorizer_ui_type_id__volatile, geany_colorizer_ui_type_id);
	}
	return geany_colorizer_ui_type_id__volatile;
}


static void geany_colorizer_ui_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GeanyColorizerUI * self;
	self = GEANY_COLORIZER_UI (object);
	switch (property_id) {
		case GEANY_COLORIZER_UI_COMBO_LEXER:
		g_value_set_object (value, geany_colorizer_ui_get_combo_lexer (self));
		break;
		case GEANY_COLORIZER_UI_COMBO_STYLE:
		g_value_set_object (value, geany_colorizer_ui_get_combo_style (self));
		break;
		case GEANY_COLORIZER_UI_CURRENT_LEXER:
		g_value_set_int (value, geany_colorizer_ui_get_current_lexer (self));
		break;
		case GEANY_COLORIZER_UI_CURRENT_STYLE:
		g_value_set_int (value, geany_colorizer_ui_get_current_style (self));
		break;
		case GEANY_COLORIZER_UI_CURRENT_FOREGROUND_COLOR:
		g_value_set_int (value, geany_colorizer_ui_get_current_foreground_color (self));
		break;
		case GEANY_COLORIZER_UI_CURRENT_BACKGROUND_COLOR:
		g_value_set_int (value, geany_colorizer_ui_get_current_background_color (self));
		break;
		case GEANY_COLORIZER_UI_FONT_BOLD:
		g_value_set_boolean (value, geany_colorizer_ui_get_font_bold (self));
		break;
		case GEANY_COLORIZER_UI_FONT_ITALIC:
		g_value_set_boolean (value, geany_colorizer_ui_get_font_italic (self));
		break;
		case GEANY_COLORIZER_UI_FONT_UNDERLINE:
		g_value_set_boolean (value, geany_colorizer_ui_get_font_underline (self));
		break;
		case GEANY_COLORIZER_UI_USE_COMMON_BACKGROUND:
		g_value_set_boolean (value, geany_colorizer_ui_get_use_common_background (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_colorizer_ui_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GeanyColorizerUI * self;
	self = GEANY_COLORIZER_UI (object);
	switch (property_id) {
		case GEANY_COLORIZER_UI_CURRENT_LEXER:
		geany_colorizer_ui_set_current_lexer (self, g_value_get_int (value));
		break;
		case GEANY_COLORIZER_UI_CURRENT_STYLE:
		geany_colorizer_ui_set_current_style (self, g_value_get_int (value));
		break;
		case GEANY_COLORIZER_UI_CURRENT_FOREGROUND_COLOR:
		geany_colorizer_ui_set_current_foreground_color (self, g_value_get_int (value));
		break;
		case GEANY_COLORIZER_UI_CURRENT_BACKGROUND_COLOR:
		geany_colorizer_ui_set_current_background_color (self, g_value_get_int (value));
		break;
		case GEANY_COLORIZER_UI_FONT_BOLD:
		geany_colorizer_ui_set_font_bold (self, g_value_get_boolean (value));
		break;
		case GEANY_COLORIZER_UI_FONT_ITALIC:
		geany_colorizer_ui_set_font_italic (self, g_value_get_boolean (value));
		break;
		case GEANY_COLORIZER_UI_FONT_UNDERLINE:
		geany_colorizer_ui_set_font_underline (self, g_value_get_boolean (value));
		break;
		case GEANY_COLORIZER_UI_USE_COMMON_BACKGROUND:
		geany_colorizer_ui_set_use_common_background (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




